apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apachesvc.name }}-internal
spec:
  ports:
    - port: 8080 # Inside the cluster, what port does the service expose?
      targetPort: 80 # Which port do pods selected by this service expose?
      protocol: TCP
      name: http
  selector:
    {{- with .Values.apachedeployment.labels }}
    {{ toYaml . }}
    {{- end }}
